// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvGWd4orEvVqiMMEo0_jkICBHjEbpYh4',
    appId: '1:942864598089:web:4930ac00d9975e399f6b98',
    messagingSenderId: '942864598089',
    projectId: 'chat-app-5c819',
    authDomain: 'chat-app-5c819.firebaseapp.com',
    storageBucket: 'chat-app-5c819.appspot.com',
    measurementId: 'G-BR1HHW5GHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqB6_rqjOMyRCiJoUEflU5Bcxhuw-QkQ',
    appId: '1:942864598089:android:406ca6599a9e9fd39f6b98',
    messagingSenderId: '942864598089',
    projectId: 'chat-app-5c819',
    storageBucket: 'chat-app-5c819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYLBFM2FhWB6Ayr6o3Y5TCVCVM8K_SP4',
    appId: '1:942864598089:ios:573194216485fd189f6b98',
    messagingSenderId: '942864598089',
    projectId: 'chat-app-5c819',
    storageBucket: 'chat-app-5c819.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYLBFM2FhWB6Ayr6o3Y5TCVCVM8K_SP4',
    appId: '1:942864598089:ios:bccfad5d6d407e389f6b98',
    messagingSenderId: '942864598089',
    projectId: 'chat-app-5c819',
    storageBucket: 'chat-app-5c819.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
